catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ProductListPage.as_view(), name='product-list'),
    path('<pk>/', views.ProductDetailView.as_view(), name='product-detail'),
]

productdb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('products/', include('catalog.urls'), name='product-app'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


PRICE_CHOICES = {
    "clearance":"Clearance (.97)",  # Ends in .97
    "manager-discounts":"Manager Special (.88 or .00)",  # Ends in .88 or .00
    "last-batch":"Last Batch (*)",  # Has an asterisk (*) at the end
    "regular":"Regular Price",  # Ends in a 9
}

UNITS_CHOICES = {
    "lb":"lb",
    "oz": "oz",
    "pt": "pt",
    "gal": "gal",
    "fl oz": "fl. oz.",
    "kg":"kg",
    "g":"g",
    "mg":"mg",
    "l":"l",
    "ml":"mL",
    "km":"km",
    "m":"m",
}


class Brand(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Brand"
        verbose_name_plural = "Brands"


# Create your models here.
class Product(models.Model):
    product_brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=100)
    product_sku = models.CharField(max_length=100)
    product_upc = models.CharField(max_length=100)
    product_weight = models.DecimalField(max_digits=5, decimal_places=2)
    product_weight_units = models.CharField(max_length=100, choices=UNITS_CHOICES.items())
    product_status = models.CharField(max_length=100, choices=PRICE_CHOICES.items())

    image = models.ImageField(upload_to=f'products/', null=True, blank=True)

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def get_history(self):
        return PriceHistory.objects.filter(parent_product=self.pk)

    def __str__(self):
        return f"{self.product_brand} - {self.product_name}"


class Store(models.Model):
    owner = models.CharField(max_length=100)
    store_name = models.CharField(max_length=255)
    store_address = models.CharField(max_length=255)
    store_city = models.CharField(max_length=255)
    store_provence = models.CharField(max_length=255)
    store_postal_code = models.CharField(max_length=255)
    store_country = models.CharField(max_length=255)

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.store_name


class PriceHistory(models.Model):
    parent_product = models.ForeignKey(Product, on_delete=models.CASCADE)
    location = models.ForeignKey(Store, on_delete=models.CASCADE)
    quantity = models.IntegerField()  # -1 means alot, positive int is actual quantity
    price = models.DecimalField(max_digits=10, decimal_places=2)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.parent_product.product_name} ({self.price})"

catalog/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView

from .models import Product, PriceHistory

# Create your views here.
class ProductListPage(LoginRequiredMixin, ListView):
    model = Product
    template_name = "catalog/index.html"
    context_object_name = "products"
    paginate_by = 100  # if pagination is desired


class ProductDetailView(DetailView):
    model = Product
    template_name = "catalog/product_detail.html"
    context_object_name = "product"

catalog/templates/catalog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ProductDB</title>
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
</head>

<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-green-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">ProductDB</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <a class="mr-5 hover:text-gray-900">Home</a>
      <a class="mr-5 hover:text-gray-900">About</a>
      <a class="mr-5 hover:text-gray-900" href="/products/">Shop</a>
      <a class="mr-5 hover:text-gray-900">Contact</a>
    </nav>
    <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Login
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </button>
  </div>
</header>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}

{% block content %}
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto">
            <div class="flex -m-4">
                {% for item in products %}
                    <div class="lg:w-1/4 md:w-1/2 p-4 h-full w-full">
                        <a class="block relative rounded overflow-hidden" href="{% url 'product-detail' item.id %}">
                            <img alt="ecommerce" class="object-cover object-center w-full h-full block"
                                 src="http://127.0.0.1:8000/media/{{ item.image }}">
                        </a>
                        <div class="mt-4">
                            <h3 class="text-gray-700 text-xs tracking-widest title-font mb-1" href="{% url 'product-detail' item.id %}">{{ item.product_brand }}</h3>
                            <h2 class="text-gray-900 title-font text-lg font-medium" href="{% url 'product-detail' item.id %}">{{ item.product_name }}</h2>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block content %}

    <section class="text-gray-600 body-font overflow-hidden">
        <div class="container px-5 py-24 mx-auto">
            <div class="lg:w-4/5 mx-auto flex flex-wrap">
                <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
                     src="http://127.0.0.1:8000/media/{{ product.image }}">
                <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
                    <h2 class="text-sm title-font text-gray-500 tracking-widest">{{ product.product_brand }}</h2>
                    <h1 class="text-gray-900 text-3xl title-font font-medium mb-1">{{ product.product_name }}</h1>
                    <div class="flex border-t border-gray-200 py-2">
                        <span class="text-gray-500">Size</span>
                        <span class="ml-auto text-gray-900">{{ product.product_weight }} {{ product.product_weight_units.upper }}</span>
                    </div>
                    <div class="flex border-t border-gray-200 py-2">
                        <span class="text-gray-500">Status</span>
                        <span class="ml-auto text-gray-900">{{ product.product_status.capitalize }}</span>
                    </div>
                    <div class="flex border-t border-gray-200 py-2">
                        <span class="text-gray-500">SKU</span>
                        <span class="ml-auto text-gray-900">{{ product.product_sku }}</span>
                    </div>
                    <div class="flex">
                        <span class="title-font font-medium text-2xl text-gray-900">${{ product.pricehistory_set.all.last.price }}</span>
                        <button class="flex ml-auto text-white bg-green-500 border-0 py-2 px-6 focus:outline-none hover:bg-green-600 rounded">
                            Add to Cart
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </section>



    <section class="text-gray-600 body-font overflow-hidden">
        <div class="container px-5 py-24 mx-auto">
            <div class="lg:w-4/5 mx-auto flex flex-wrap">
                <table class="table-auto w-full text-left whitespace-no-wrap">
                    <thead>
                    <tr>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">
                            Store
                        </th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            Quantity
                        </th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            Date
                        </th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            Price
                        </th>
                        {#                        <th class="w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br"></th>#}
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in product.pricehistory_set.all reversed %}
                        <tr>
                            <td class="px-4 py-3">{{ item.location }}</td>
                            {% if item.quantity <= -1 %}
                                <td class="px-4 py-3">Many</td>
                            {% else %}
                                <td class="px-4 py-3">{{ item.quantity }}</td>
                            {% endif %}

                            <td class="px-4 py-3">{{ item.date_created }}</td>
                            <td class="px-4 py-3 text-lg text-gray-900 text-right">${{ item.price }}</td>
                            {#            <td class="w-10 text-center">#}
                            {#              <input name="plan" type="radio">#}
                            {#            </td>#}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>
{% endblock %}